package-lock.json
package.json
src/auth/auth.d.ts
src/auth/hooks/useAuth.ts
src/auth/ledger/AccessWithLedgerForm.tsx
src/config/constants.ts

Same as [Station #39](https://github.com/terra-money/station/pull/39) for the extension

Connect Ledger with bluetooth

---

src/pages/wallet/AssetChain.module.scss
src/pages/wallet/AssetList.module.scss
src/pages/wallet/AssetList.tsx
src/pages/wallet/AssetPage.module.scss
src/pages/wallet/AssetPage.tsx
src/txs/InterchainTx.tsx
src/txs/Tx.tsx

fixes from figma design:
- remove hover state from AssetChain component
- change add tokens styling
- change send/receive button layout on AssetPage
- remove tax data check

Fix: asset list bugs and layout

---

src/app/components/AddressTable.tsx
src/pages/wallet/ReceivePage.module.scss
src/pages/wallet/SendPage.module.scss
src/pages/wallet/Wallet.module.scss

cherry picked changes form station:
1. sort addresses by if asset is present
2. change back button layout

feat: layouts asset ordering

---

src/pages/wallet/SendPage.tsx

fix: add decimal places from denom

---

src/app/InitBankBalance.tsx

St 356 cannot read properties of undefined reading chains

---

src/app/InitBankBalance.tsx

Reverts terra-money/station-extension#101

Revert "St 356 cannot read properties of undefined reading chains"

---

src/pages/wallet/NetWorth.tsx

Only display buy button on mainnet.

fix: buy button network

---

src/components/layout/Page.tsx
src/pages/gov/ProposalDetails.tsx
src/pages/stake/ValidatorDetails.tsx
src/txs/stake/StakeTx.tsx

Bringing in back button changes made on web to extension.

chore: back button translate

---

src/pages/wallet/AssetList.tsx
src/utils/chain.ts

translating hide low balance functionality from Station web:
https://github.com/terra-money/station/pull/384/commits/b12c830fdf781ffcb0649bfbb9339dd322aa0146

fix: hide low balance functionality

---

package-lock.json
package.json
src/index.tsx
src/utils/sentry/setupSentry.ts
tsconfig.json

ST-440-implement-sentry

---

src/pages/wallet/Asset.tsx

fix: send fixed length to asset read component

---

src/pages/custom/ManageCustomTokens.tsx
src/pages/wallet/AssetList.tsx

…d (#399)
* fix tokens disappearing with low balance
* fix manage tokens list

ST-437: tokens disappearing

---

public/firefox.manifest.json
public/manifest.json
src/extension/modules/ConfirmTx.tsx

This reverts commit ffa45086a255e02b66e07f8001baa5073983563c.

Revert "ST-429: fix gas estimation for external txs (#147)"

---

src/data/queries/tendermint.ts
src/txs/utils.ts

Handling axios and destructure undefined errors already implemented in web:
https://github.com/terra-money/station/pull/415/files

feat: axios error handling

---

src/pages/wallet/AssetPage.module.scss
src/pages/wallet/AssetPage.tsx

https://github.com/terra-money/station-extension/assets/18373990/e67a3aee-6c1d-4742-aec4-d10e0948b8bf

fixed no scroll issue on an Asset page

---

src/pages/wallet/AssetPage.module.scss
src/pages/wallet/AssetPage.tsx

same as https://github.com/terra-money/station/pull/429

FIX: chain list overlapping 

---

src/pages/wallet/Asset.tsx
src/pages/wallet/Vesting.tsx

https://github.com/terra-money/station-extension/assets/30275692/39b81d6a-8cc4-4c67-b101-aefc06f1dfeb
https://github.com/terra-money/station-extension/assets/30275692/bdb573cb-ba9d-45fc-8606-88e631cfcb1e

fix: vesting token component

---

src/app/InitNetworks.tsx
src/app/sections/LCDSetting.tsx
src/auth/hooks/useAuth.ts
src/auth/hooks/useNetwork.ts
src/auth/networks/AddNetworkForm.tsx
src/components/layout/ChainFilter.tsx
src/components/layout/SettingsSelector.tsx
src/data/queries/staking.ts
src/extension/modules/ConfirmNewChain.tsx
src/extension/modules/ConfirmTx.tsx
src/pages/wallet/AssetList.tsx
src/pages/wallet/AssetPage.tsx
src/pages/wallet/IbcSendBackTx.tsx
src/txs/stake/StakeTx.tsx

https://sentry.io/organizations/terraform-labs-y3/issues/4219022307/?query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=5

fix: property undefined chainID error

---

scripts/contentScript.js

with the `?? {}` check in this file, `npm run build` errs out.  This change will fix the issue.

fix: build error

---

src/app/InitBankBalance.tsx
src/pages/wallet/AssetList.tsx
src/pages/wallet/AssetPage.tsx

Moving changes over from:
https://github.com/terra-money/station/pull/421/files
Below is an example with token: `factory:kujira13y8hs83sk0la7na2w5g5nzrnjjpnkvmd7e87yd35g8dcph7dn0ksenay2a:ulp`

fix: tokens with :

---

src/data/token.tsx
src/pages/wallet/AssetList.tsx
src/pages/wallet/AssetPage.tsx

https://github.com/terra-money/station-extension/assets/30275692/9002c59a-0c12-4c19-9565-cee972332040
https://github.com/terra-money/station-extension/assets/30275692/d7d3a616-d55d-461f-8760-4450f091f4bd

fix: non-whitelisted tokens

---

src/data/queries/coingecko.ts
src/pages/wallet/Asset.tsx
src/pages/wallet/AssetChain.tsx
src/pages/wallet/AssetList.tsx
src/pages/wallet/AssetPage.tsx

https://github.com/terra-money/station-extension/assets/30275692/dee6dd7f-e978-4b2f-bdaf-ea534d9ae589
https://github.com/terra-money/station-extension/assets/30275692/52da45e7-00c2-41bc-a6fe-7c50d9e1e503

fix: avoid balance error if TFM not responding

---

src/pages/wallet/AssetChain.tsx

Same as https://github.com/terra-money/station/pull/454

ST-582: show disabled network name

---

src/app/InitNetworks.tsx
src/auth/hooks/useNetwork.ts
src/auth/networks/AddNetworkForm.tsx
src/auth/scripts/network.ts
src/components/form/ChainList.tsx
src/data/Terra/TerraAssets.ts
src/data/queries/chains.ts
src/data/queries/ibc.ts
src/data/settings/CustomNetworks.ts
src/extension/storage.ts
src/pages/wallet/IbcSendBackTx.tsx
src/pages/wallet/SendPage.tsx
src/txs/validate.ts
src/types/network.d.ts
src/utils/coin.ts
src/utils/localStorage.ts

Same as https://github.com/terra-money/station/pull/453

Use new IBC channels

---

src/data/queries/chains.ts
src/data/queries/ibc.ts
src/pages/wallet/IbcSendBackTx.tsx
src/pages/wallet/SendPage.tsx

Same as https://github.com/terra-money/station/pull/464

ST-596: fix ics20 send back

---

src/data/queries/ibc.ts
src/pages/wallet/IbcSendBackTx.tsx

Same as https://github.com/terra-money/station/pull/466

fix kujira factory IBC tokens

---

src/components/form/Input.tsx
src/pages/wallet/IbcSendBackTx.tsx
src/pages/wallet/SendPage.tsx
src/styles/_customize.scss
src/txs/gov/DepositForm.tsx
src/txs/gov/SubmitProposalForm.tsx
src/txs/stake/QuickStakeForm.tsx
src/txs/stake/StakeForm.tsx
src/txs/swap/TFMSwapForm.tsx
src/txs/wasm/ExecuteContractForm.tsx
src/txs/wasm/InstantiateContractForm.tsx

amount inputs should only accept number characters and `.`.

feat: validate amount inputs

---

src/extension/auth/SelectWallets.tsx

Add test id to that specific button for easier testing

Changes: Added test id to modal button

---

package-lock.json
package.json

This PR update station-connector to include the fix made here: https://github.com/terra-money/wallet-kit/pull/11

FIX: update Station connector

---

public/manifest.json
src/app/sections/CoinTypeMnemonicForm.tsx
src/app/sections/CoinTypePasswordForm.tsx
src/components/feedback/Modal.module.scss

hotfix: injective support - fix text, overflow scroll

---

package.json
public/manifest.json
src/data/external/osmosis.ts

fix: osmosis api

---

public/manifest.json
src/data/queries/tx.ts
src/data/query.ts
src/txs/Tx.tsx

feat: estimate osmosis gas at run time

---

public/manifest.json
src/extension/update/ChangeLogModal.tsx

Sync 8.0.7.1
